### ISSUE TITLE
[BUG]: Plugin update broke obsidian

### ISSUE THREAD

**Issue by vorpalvorpal** [Falcion/UNITADE.md#63] opened 2024-05-26 01:15 UTC
### What the essence of the bug

I just updated this plugin to version 2.2.1 (sorry, I'm not sure what previous version I had installed, but I update my plugins fairly regularly so I suspect it was 2.2.0). Once updated, unitade made obsidian unresponsive. I restarted Obsidian but it stayed on the 'loading plugins' startup stage for a minute or so before I killed it. I then removed the unitade folder and then obsidian worked fine again. I then reinstalled unitade but without any file extensions selected, and obsidian worked fine again.

I use unitade for viewing .Rmd, .Qmd and .Yaml files.

I have lots of other plugins installed so it could be due to a clash between unitade and the other plugins.

### Version of an project's essence

2.2.1

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment] 2024-05-26 20:07
I repeated the process of updating versions in the order "2.1.1→2.2.1" (from and to), no errors of this nature were observed: there is a possibility that the plugin was most likely on version "1.\*.\*", which has fundamental differences and after which the project was redone from scratch, I believe that most likely the problem lies precisely in these two “generations” of the plugin and the fact that you switched from the first generation to the second is most likely in the context of your bug.

I will leave this issue open for a while, if the bug repeats, I will be glad if you write about your situation and a more detailed way to repeat the bug: thanks for your contribution and use of the project.

**Comment by Souloid** [comment] 2024-05-28 21:29
I have the same issue. I have UNITADE installed for viewing .txt files and **my current version of UNITADE is 2.1.2**. When I update UNITADE obsidian gets stuck and is no longer responsive. If I restart it it gets stuck on "loading plugins". The only way I could resolve this was to remove the .obsidian folder and restarting and resyncing my vault.

**Comment by Falcion** [comment] 2024-05-29 01:45
How did you install the update, through third-party plugins or through the application's built-in system?

**Comment by Souloid** [comment] 2024-05-29 02:45
> How did you install the update, through third-party plugins or through the application's built-in system?

Through the obsidian desktop application (checking for updates and then clicking update).

**Comment by Falcion** [comment] 2024-05-29 04:07
I tried to update the plugin in every possible way (within the second global versions): surprisingly there were no errors or problems with launching, I tried it on Windows 10/11, everything was also successful.

```console
Total plugin setup: 18ms
unitade: 18ms
```

I assume that there are two options: when updating the plugin, there is a chance that the plugin is launched on an already running plugin (the functionality of the old one does not go away) and because of this there is a massive influx of critical errors (file creation modals, modification of the extension registry), reconnection of Codemirrors, which most likely can cause error.

The second option is simpler, but less likely - some external plugin “synergies” with UNITADE and causes such interesting errors.

**Current solution:**
If you are experiencing a similar problem, delete the config file and the executable file ("data.json" and "main.js") in the plugin folder (".obsidian/"→"/plugins/"→"/unitade/").

**Comment by Souloid** [comment] 2024-05-29 06:36
> I tried to update the plugin in every possible way (within the second global versions): surprisingly there were no errors or problems with launching, I tried it on Windows 10/11, everything was also successful.
> 
> ```
> Total plugin setup: 18ms
> unitade: 18ms
> ```
> 
> I assume that there are two options: when updating the plugin, there is a chance that the plugin is launched on an already running plugin (the functionality of the old one does not go away) and because of this there is a massive influx of critical errors (file creation modals, modification of the extension registry), reconnection of Codemirrors, which most likely can cause error.
> 
> The second option is simpler, but less likely - some external plugin “synergies” with UNITADE and causes such interesting errors.
> 
> **Current solution:** If you are experiencing a similar problem, delete the config file and the executable file ("data.json" and "main.js") in the plugin folder (".obsidian/"→"/plugins/"→"/unitade/").

Would this solution reset the plugin? or would it break it?

I was considering trying to uninstall the plugin, and installing the latest release from the github page. Doing that however, would mean I would no longer be able to test whether the issue is resolved in the future.

At the moment I am fine with not updating the plugin, it's functioning and I can help test if an implemented solution works.

Would you like me to continue using 2.1.2?

**Comment by Falcion** [comment] 2024-05-29 08:23
**The solution presented in this issue will simply remove the entire plugin and leave only the manifest so you can try updating the plugin and "installing it from scratch"**.

- I will update the comment with the solution for greater accuracy.

The main problem with this bug is that I have little context for it and I cannot repeat it, so the universal solution that I can offer is the following:

1. Forcefully delete all files associated with the plugin (".obsidian/"→"/plugins/"→"/unitade/");
2. Download the plugin in any convenient way (the author of this topic, as I understand it, then installed it again via the OBSIDIAN's community plugins browser).

At the moment, this is the only solution known to me that I can offer and which was checked by another person, what about updates: if the current version fully meets the requirements, then it is not necessary for you to update.

**Comment by Falcion** [comment] 2024-05-29 08:52
> **The solution presented in this issue will simply remove the entire plugin and leave only the manifest so you can try updating the plugin and "installing it from scratch"**.
> 
> * I will update the comment with the solution for greater accuracy.
> 
> The main problem with this bug is that I have little context for it and I cannot repeat it, so the universal solution that I can offer is the following:
> 
> 1. Forcefully delete all files associated with the plugin (".obsidian/"→"/plugins/"→"/unitade/");
> 2. Download the plugin in any convenient way (the author of this topic, as I understand it, then installed it again via the OBSIDIAN's community plugins browser).
> 
> At the moment, this is the only solution known to me that I can offer and which was checked by another person, what about updates: if the current version fully meets the requirements, then it is not necessary for you to update.

**If this happens again and you have the opportunity, do the following:**
1. Ctrl+Shift+I (open the developer console);
2. See if there is anything in the console (if it opens at all), this may provide more context for solving this problem.

**Comment by vorpalvorpal** [comment] 2024-05-29 11:45
Sorry. I know how frustrating it can be when you can't reproduce a bug.

Just to clarify my original post. I deleted the plugin then reinstalled it and obsidian worked fine. However, if I then changed the files detected back to the ones that I want it to use (yml, qmd, rmd) it bricks obsidian.

**Comment by Axialer** [comment] 2024-05-29 13:38
I've been updating the plugin from version 1.0.2 to Windows 11 and I'm fine... If you have a problem with the installation, then most likely the problem is not in the plugin, but on the client side, because even when updating from one generation of versions to another, and even in such urgent circumstances, the plugin works.

**Comment by Souloid** [comment] 2024-05-29 15:20
> I've been updating the plugin from version 1.0.2 to Windows 11 and I'm fine... If you have a problem with the installation, then most likely the problem is not in the plugin, but on the client side, because even when updating from one generation of versions to another, and even in such urgent circumstances, the plugin works.

I had this update issue happen to me both on my laptop and desktop (both windows 10). But both of them were updating from version 2.1.2 not from a fresh install.

**Comment by Souloid** [comment] 2024-05-29 15:22
> > **The solution presented in this issue will simply remove the entire plugin and leave only the manifest so you can try updating the plugin and "installing it from scratch"**.
> > 
> > * I will update the comment with the solution for greater accuracy.
> > 
> > The main problem with this bug is that I have little context for it and I cannot repeat it, so the universal solution that I can offer is the following:
> > 
> > 1. Forcefully delete all files associated with the plugin (".obsidian/"→"/plugins/"→"/unitade/");
> > 2. Download the plugin in any convenient way (the author of this topic, as I understand it, then installed it again via the OBSIDIAN's community plugins browser).
> > 
> > At the moment, this is the only solution known to me that I can offer and which was checked by another person, what about updates: if the current version fully meets the requirements, then it is not necessary for you to update.
> 
> **If this happens again and you have the opportunity, do the following:**
> 
> 1. Ctrl+Shift+I (open the developer console);
> 2. See if there is anything in the console (if it opens at all), this may provide more context for solving this problem.

I followed your earlier instructions and deleted the Data.JSON and Main.JS from the plugin's folder. I then updated through the obsidian app and it worked. I then checked the contents of the plugin folder and only main.js was reinstalled.

Plugin works fine as far as I can tell (I can view txt files).

**Comment by Falcion** [comment] 2024-05-29 17:54
Then I close this topic, but do not block it for future messages: it remains pinned for the FAQ and to avoid duplicate issues.

**Closed by Falcion** 2024-05-29 17:54 UTC
Labels: help-wanted, bug, status/considered, priority/medium, reason/unknown
