### ISSUE TITLE
[FEATURE]: Can add a plain text view?

### ISSUE THREAD

**Issue by ZSkycat** [Falcion/UNITADE.md#73] opened 2024-09-15 02:50 UTC
### What the essence of your feature request

Plain text will be rendered as markdown in reading view.
I want it to be displayed as plain text.

In txt file:
```
Steam\userdata\*\*\remote
#Key
```

In reading view:
```
Steam\userdata**\remote
#Key (>> It becomes a nasty tag)
```

### On what OS you want to maintain your request.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment] 2024-09-15 09:47
Thanks for opening the issue!

This problem occurs because the extension system (which the plugin works on) reads the .TXT file into the .MD text renderer.

There is currently no solution for this issue, so I plan to integrate a full-fledged syntax highlighting system and a "code editor" based on "Monaco Editor" technology, since CM (Codemirrors) has long ceased to support the functionality of its own renderer.

In the near future, I plan to start developing this integration, the progress can be checked in the branch:\
https://github.com/Falcion/UNITADE.md/tree/feature/syntax-highlighting

**Comment by pemre** [comment] 2024-10-24 21:46
# Rendering "txt", "yml", "csv" and all file types as plain text in Obsidian, using UNITADE

I use a trick to render "txt", "yaml" (yml) and "csv" files as plain text.

## Step 1

I installed UNITADE as usual, then defined txt, yml and csv as extensions:

![image](https://github.com/user-attachments/assets/7750ec2b-a750-4ff8-ae03-078fea66a4c8)

At this point comments in yml files are rendered as H1/2/3 headers which we want to prevent...

## Step 2

Then I created a CSS snippet file, put it under "snippets" folder, and enabled it in Appearance settings:

![image](https://github.com/user-attachments/assets/b3f94c25-2a28-4428-89f7-643d43fff67f)

Here is `snippet.css` for "yml" extension, you can extend it to any other extension you want with copy/pasting the whole rule and replacing "yml" with your extension.  If you know a bit CSS, you can reuse the CSS selectors and make it efficient too:

```css
/* Note: This trick will not work when you have split view */

/* ============================ YML ============================ */

/* IF left menu (mod-left-split) has an active file with "yml" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="yml"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-content * {
    color: var(--code-normal);
    font-size: var(--font-text-size);
    font-family: var(--font-monospace);
    font-weight: normal;
}

/* IF left menu (mod-left-split) has an active file with "yml" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="yml"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-header {
    color: var(--text-accent);
}
```

## End result

This is the result:

![image](https://github.com/user-attachments/assets/7af1a695-9305-47fb-8d70-4df42d299da1)

# Notes:

1. This trick **will not work when you have split view**. I didn't spend much time to make it work to be honest. While working on yml files I don't really need split view. If anyone finds a CSS way to improve it, you're welcome to share 🤗.
2. I didn't test it much, so you may see weird behaviour. I override (cosmetically of course, CSS doesn't change the actual content) almost everything under content section. Use at your own risk.
3. I use **source mode** when I edit yml files. So rendering in classic mode still hides "#" hashtags; I can't handle it with pure CSS (at least didn't check devTools, probably not possible).

**Comment by pemre** [comment] 2024-10-24 22:00
@ZSkycat for preventing #tags becoming a rounded chip, you can add:

```css
/* IF left menu (mod-left-split) has an active file with "txt" extension */
.mod-left-split:has( .nav-file-title.is-active[data-path$="txt"] )

/* THEN its sibling (mod-root) will have overriden CSS rules */
~ .mod-root .workspace-leaf-content .cm-hashtag {
    padding: 0;
    background: none;
}
```

**Comment by Falcion** [comment] 2024-10-25 09:49
> # Rendering "txt", "yml", "csv" and all file types as plain text in Obsidian, using UNITADE
> I use a trick to render "txt", "yaml" (yml) and "csv" files as plain text.
> 
> ## Step 1
> I installed UNITADE as usual, then defined txt, yml and csv as extensions:
> ...

Didn't expect to see such a unique use of my plugin, thanks for the help, @pemre!

The plugin once attempted to implement a custom renderer using Codemirrors and CSS styles, but was unsuccessful.

@ZSkycat, purely technically, the dev version of the plugin already has the ability to work with the source code, but it requires polishing and may be "broken" on other devices.

Thanks for waiting for the release.

**Closed** 2024-11-03 18:25 UTC
Labels: enhancement ✨, main, platform/all, WIP, priority/high, feature request

**Comment by Falcion** [comment] 2024-11-03 18:31
Read more about new release related to this issue:
https://github.com/Falcion/UNITADE.md/releases/tag/v3.0.0
https://github.com/Falcion/UNITADE.md/blob/main/data/release/v3.0.0.md

**Comment by pemre** [comment] 2024-11-03 18:40
Thanks for the update! JFYI, we can't update it. Update button gives "Failedd to install" error. I uninstalled, restarted app and tried to install; still having the same error. Now I lost the previous version too :sweat_smile: :/

**Comment by Falcion** [comment] 2024-11-03 18:47
> Thanks for the update! JFYI, we can't update it. Update button gives "Failedd to install" error. I uninstalled, restarted app and tried to install; still having the same error. Now I lost the previous version too 😅 :/

The mistake was that I made a release using standard normalized semantics (starting at v*), OBSIDIAN does not accept this.

The problem is fixed, please try again.

**Comment by pemre** [comment] 2024-11-03 19:35
Thanks. I just installed. I observed some confusing issues:

* In README, it says "comma" is needed: `[...] “extensions” and type an array of extensions, separated by comma; [...]`. Source: https://github.com/Falcion/UNITADE.md/tree/main?tab=readme-ov-file#usage
* The plugin settings page says "semicolon" is needed:

![image](https://github.com/user-attachments/assets/0e340a9d-4072-4c31-bb04-3f4bf3985a19)

But actually only ">" greater/closing-tag works. :confused: 

E.g. "txt> csv> yml" 

Also: Any attempt of using comma or semicolon triggers not only one but tens of notifications in the system tray.

And I couldn't make it use any code editor yet. I still see bare markdown editor's view.

**Comment by Falcion** [comment] 2024-11-03 19:48
> In README, it says "comma" is needed: [...] “extensions” and type an array of extensions, separated by comma; [...]. Source: https://github.com/Falcion/UNITADE.md/tree/main?tab=readme-ov-file#usage

Forgot about README, will fix.

> The plugin settings page says "semicolon" is needed:

Also would edit, my bad.

> Also: Any attempt of using comma or semicolon triggers not only one but tens of notifications in the system tray.

This is a common problem, it is discussed in the issue #70, it occurs because OBSIDIAN doesn't allow me to read "input" of user as final and I have to "castrate" the input in such formations.

You can read wiki's page about silencing errors, it's functionality is down below in the settings page:
https://github.com/Falcion/UNITADE.md/wiki/Error-handling

> And I couldn't make it use any code editor yet. I still see bare markdown editor's view.
Did you enable code editor module in the settings? If you so, did you tried to "insert" extensions in it's input: restart may help.

**Comment by Falcion** [comment] 2024-11-03 19:49
Because I installed the plugin, set up, for example, this config (`data.json`):

```json
{
  "markdown_overcharge": false,
  "extensions": "txt",
  "is_case_insensitive": false,
  "is_onload": false,
  "is_onload_unsafe": false,
  "forced_extensions": "",
  "is_ignore": false,
  "ignore_extensions": "",
  "ignore_masks": "",
  "is_grouped": false,
  "grouped_extensions": "",
  "mobile_settings": {
    "enable": false,
    "extensions": "txt",
    "stable": true
  },
  "barefiling": true,
  "stable": true,
  "errors": {
    "": "Error from UNITADE plugin: Error: Attempting to register an existing view type \"\""
  },
  "debug_mode": true,
  "silence_errors": true,
  "manifest_version": "",
  "compatibility_module": true,
  "code_editor_settings": {
    "enabled": true,
    "use_default_extensions": false,
    "extensions": "dart> txt> yaml",
    "folding": true,
    "line_numbers": true,
    "word_wrapping": false,
    "minimapping": true,
    "validation_semantic": true,
    "validation_syntax": true,
    "theme": "AUTO",
    "font_size": 14,
    "font_family": "'Cascadia Code', 'Fira Code', Consolas, 'Courier New', monospace",
    "font_ligatures": true
  },
  "SYS_FONTSIZE_MAX": 32,
  "SYS_FONTSIZE_MIN": 5
}
```

And everything works:
![image](https://github.com/user-attachments/assets/c113eab7-6e8d-4a27-ae32-13c846e5aa59)

**Comment by pemre** [comment] 2024-11-03 19:56
It worked with your config, thanks! "use_default_extensions" was true... Making it false did the trick, I think... I also changed debug mode and silence errors, but I don't think that they are responsible.

**Comment by Falcion** [comment] 2024-11-03 20:01
> It worked with your config, thanks! "use_default_extensions" was true... Making it false did the trick, I think... I also changed debug mode and silence errors, but I don't think that they are responsible.

Last two are just for convenience, first one: it's an interesting problem related to OBSIDIAN and my settings, I'll also add it on my radar.

Thanks for "early-testing" my plugin!

---

**From this dialog, we got:**

1. Fix README and settings tab about semantics of "splitting" extensions;
2. Add comment about "error-spamming" in the extensions block, relate to "error silencing";
3. Fix code editor's "extensions async" display mode;
4. Add comment about how "use default extensions" work in short terms (because there are wiki for more advanced information):
5. Add "warning" about case-insensitive, if user is too reckless it can forever crash vault until disabling this feature through JSON config of plugin.

**Comment by Lexvox** [comment] 2024-11-23 12:42
Sorry for being a dunce but I have yet to understand what I have to do to view a .txt file without any formatting applied to it.

**Comment by Falcion** [comment] 2024-11-23 18:39
Use "code editor module" from "v3.*" version of plugin, you can either turn on "use default extensions" (it would use extensions from "extensions" setting block) or type custom extensions in it.

It would open files as code files (like in any code editor), more advanced instruction:

1. Download the latest version of the plugin;
2. Write in "extensions" setting (at the start of settings page):

  ```bash
  txt
  ```
  
3. Go to "code editor module," and turn it on if it is disabled, find "use default extensions" toggle and turn it on also;
4. Now plugin should treat any files with "txt" (and only "txt") extensions as code in your OBSIDIAN's vault.

**More about extensions, code editor and etc. read at the wiki:**
https://github.com/Falcion/UNITADE.md/wiki

**Comment by Lexvox** [comment] 2024-11-24 12:58
@Falcion iirc that was the default setup when I downloaded the extension, so there wasn't anything I could change.
'Code editor module' and 'use default extensions' was already enabled. Also I had already set txt in the 'extensions' setting, yet still there is some highlighting going on.
I think for context (bc maybe what I want is out of scope anyway) I have a file with a bunch of ascii art and rn the tab and () get highlighted and I want to get rid of that.

**Comment by Falcion** [comment] 2024-11-24 13:17
> @Falcion iirc that was the default setup when I downloaded the extension, so there wasn't anything I could change. 'Code editor module' and 'use default extensions' was already enabled. Also I had already set txt in the 'extensions' setting, yet still there is some highlighting going on. I think for context (bc maybe what I want is out of scope anyway) I have a file with a bunch of ascii art and rn the tab and () get highlighted and I want to get rid of that.

Now I understand what you are talking about, unfortunately I can't do anything about this problem: it is "installed" on the editor side of the Monaco Editor technology (the same one that VS Code uses, in which a similar problem occurs sometimes, I checked it myself).

Maybe in theory there really is a solution, but I don't know about it, unfortunately: you can try the solution proposed in this discussion by installing CSS styles (via snippet) and rendering the file via just OBSIDIAN.

![image](https://github.com/user-attachments/assets/101a3b24-cc7f-47ad-8843-91ef2aa52458)
![image](https://github.com/user-attachments/assets/31e93b1d-d800-47da-b3f7-b2ea6ff15e8f)

> [!Note]
> I know this is not the best solution, but you can use "PITCH-LIGHT" theme, it doesn't show any validations errors like this.

![image](https://github.com/user-attachments/assets/4a7cac5b-5637-45d6-bf84-48c63a337e78)

**Comment by Lexvox** [comment] 2024-11-24 13:53
> Now I understand what you are talking about

Yeah I should've been clearer about what I was trying 2 do.
Thank you very much for the extensive reply, I highly appreciate it!
Gonna look into adding the css 2 my snippets then.
cheers
